version: '2'
services:
    beaker-app:
        image: beaker
        external_links:
            - beaker-mongodb:mongodb
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=beaker
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    beaker-mongodb:
        extends:
            file: mongodb.yml
            service: beaker-mongodb
