version: '2'
services:
    beaker-mongodb:
        container_name: beaker-mongodb
        image: mongo:3.2.10
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/beaker/mongodb/:/data/db/
